# Generated by Django 4.1.3 on 2023-12-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chavespix',
            fields=[
                ('chavepix', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('banco', models.CharField(default='', max_length=4)),
                ('conta', models.CharField(default='', max_length=20)),
                ('titular', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enviapix',
            fields=[
                ('idtrans', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('tstrans', models.DateTimeField(auto_now=True)),
                ('iptrans', models.CharField(default='127.0.0.1', max_length=25)),
                ('chavepix', models.CharField(max_length=100)),
                ('banco', models.CharField(blank=True, max_length=4)),
                ('conta', models.CharField(blank=True, max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=1.0, max_digits=22)),
                ('titular', models.CharField(blank=True, max_length=100)),
                ('resposta', models.CharField(blank=True, max_length=500)),
                ('minhaconta', models.CharField(max_length=30)),
                ('meunome', models.CharField(max_length=100)),
            ],
        ),
    ]
